buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
    implementation 'com.capacitorjs:core:6.2.0'
    implementation 'com.capacitorjs:android:6.2.0'
        classpath 'com.android.tools.build:gradle:8.7.2'
    }
}

apply from: 'variables.gradle'

allprojects {
    repositories {
        google()
        mavenCentral()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}